---
configure_dotfiles: true
configure_terminal: false
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: git@github.com:bikramtuladhar/dotfiles-.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Projects/GitHub/dotfiles-
dotfiles_files:
  - .gitignore
  - .inputrc
  - .osx
  - .gitconfig

homebrew_installed_packages:
  - git
  - gh
  - nvm
  - mas
  - wget
  - curl
  - pyenv
  - libpq
  - mysql-client

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - orbstack
  - google-chrome
  - slack
  - logi-options-plus
  - jetbrains-toolbox
  - angry-ip-scanner
  - flycut
  - keka
  - owasp-zap
  - postman
  - skype
  - vlc
  - zerotier-one
  - android-file-transfer
  - sublime-text
  - balenaetcher
  - cloudflare-warp

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: 
  - { id: 497799835, name: "Xcode (15.4)" }
  - { id: 1429033973, name: "RunCat (11.3)" }
  - { id: 409201541, name: "Pages (14.1)" }
  - { id: 409183694, name: "Keynote (14.1)" }
  - { id: 409203825, name: "Numbers (14.1)" }
  - { id: 1480068668, name: "Messenger (215.3)" }
  - { id: 1147396723, name: "WhatsApp Desktop (24.15.1)" }
  - { id: 937984704, name: "Amphetamine (5.3.2)" }
  - { id: 1475387142, name: "Tailscale (1.70.0)" }
  - { id: 1352778147, name: "Bitwarden (2024.7.1)" }
  - { id: 1451685025, name: "WireGuard (1.0.16)" }
  - { id: 1295203466, name: "Microsoft Remote Desktop (10.9.9)" }

mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
